from .sync import *
from .stop import *
from .reply_commands import *
from .settings import *
from .code import *
from .avatar import *
from .clap import *
from .edenpatch import *
from .gamebanana import *
from .it import *
from .list_brazil import *
from .purge import *
from .rename_channel import *
from .role import *
from .toggle_bot_response import *
from .user_count import *
from .uwu import *
from .you_are_going_to_brazil import *
from .zoe import *
from .guess import *
from .goofy_translate import *
